const skills = [
  { name: 'JavaScript', type: 'language' },
  { name: 'React', type: 'framework' },
  { name: 'HTML/CSS', type: 'language' },
  { name: 'UI/UX Design', type: 'tool' },
  { name: 'Next.js', type: 'framework' },
  { name: 'Tailwind CSS', type: 'framework' },
  { name: 'Firebase', type: 'tool' },
  { name: 'Git', type: 'tool' },
  { name: 'Node', type: 'framework' },
  { name: 'Python', type: 'language' },
  { name: 'Neo4j', type: 'framework' },
  { name: 'pandas', type: 'framework' },
  { name: 'CI/CD', type: 'tool' },
  { name: 'sci-kit learn', type: 'framework' },
  { name: 'TypeScript', type: 'language' },
  { name: 'Figma', type: 'tool' },
  { name: 'Sass/SCSS', type: 'framework' },
  { name: 'Java', type: 'language' },
  { name: 'SQL', type: 'language' },
  { name: 'PostgreSQL', type: 'framework' },
  { name: 'Swift', type: 'language' },
  { name: 'Three.js', type: 'framework' },
  { name: 'R', type: 'language' },
  { name: 'Jira', type: 'tool' },
]

export default skills
